config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, length: { maximum: 105}, format: {with:VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def placeholder
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @articles = @user.articles
  end
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to HS2Gaming #{@user.username}, You have successfully signed up"
      redirect_to articles_path
    else
      render 'new'
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "your account has been updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravitar_for(user, options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravitar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravitar_url, alt: user.username, class: "rounded bg-dark my-2 mx-auto d-block")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="card-body">
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Author</th>
        <th scope="col">Created</th>
        <th scope="col">Updated</th>
        <th scope="col">Links</th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= link_to article.title, article_path(article), class: "text-secondary" %></td>
          <td><%= truncate(article.description, length: 50) %></td>
          <td><%= link_to article.user.username, user_path(article.user) %></td>
          <td><%= time_ago_in_words(article.created_at) %> ago</td>
          <td><%= time_ago_in_words(article.updated_at) %> ago</td>
          <td><%= link_to 'View', article_path(article) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>

      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-white rounded", local: true) do | f | %>
        <div class= "form-group row mt-4">
          <%= f.label :title, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control", placeholder: "Title of Article" %>
          </div>
        </div>

        <div class= "form-group row">
          <%= f.label :description, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_area :description, rows: "10", class: "form-control", placeholder: "Description of Article" %>
          </div>
        </div>

        <div class= "form-group row justify-content-md-center">
          <%= f.submit class: "col-2 btn btn-success" %>
        </div>
        <div class="card-footer text-muted">
          <a href=<%= articles_path() %> class="btn btn-secondary"> Return</a>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="card text-center mt-4">
  <div class="card-header">
    <h2>Update Article</h2>
  </div>
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="card text-center mt-4">
  <div class="card-header">
    <h2>Forum</h2>
  </div>
  <%= render 'article' %>
  <div class="card-footer text-muted">
    <a href=<%= new_article_path() %> class="btn btn-success"> New</a>
  </div>
</div>

app/views/articles/new.html.erb
<div class="card text-center mt-4">
  <div class="card-header">
    <h2>Create a new Article</h2>
  </div>
  <%= render 'form' %>

</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="card text-center mt-4">
    <div class="card-header">
      <h2>Showing Article Details</h2>
      <h3>From <%=@article.user.username %></h3>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%=@article.title %></h5>
      <div class="text-left">
        <p class="card-text text-left"><%=simple_format(@article.description) %></p>
      </div>
      <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-success" %>
      <%= link_to 'Delete',  article_path(@article), method: :delete, data: { confirm:"Are you sure?"}, class: "btn btn-danger" %>
      <%= link_to 'Return', articles_path(), class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div id="page-content">
</div>
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; EriksenOnline Web Dev</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do | name, msg | %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!-- <a class="navbar-brand" id="logo" href="#">HS2Gaming</a> -->
  <%= link_to "hs2gaming", root_path, class: "navbar-brand", id: "logo"  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <!-- <a class="nav-link" href="#">Forums <span class="sr-only">(current)</span></a> -->
        <%= link_to "Forums", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <!-- <a class="nav-link" href="#">Forums <span class="sr-only">(current)</span></a> -->
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li> -->
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title> Landing Page </title>
  </head>
  <body>
    <h1> This page is under construction. </h1>
    <h2> Please try again later!</h2>
    <%= link_to 'Forums', articles_path %> |
    <%= link_to 'home', root_path %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container-fluid" id="home-container">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">HS2Gaming</h1>
      <p class="lead">Welcome to HS2Gaming!</p>
      <hr class="my-4">
      <p>The Website is still under construction but please leave some input in our forums!</p>
      <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
    </div>
  </div>
</div>

app/views/pages/placeholder.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title> Landing Page </title>
  </head>
  <body>
    <h1> The game is currently unnavailable. </h1>
    <h1> Please try again later!</h1>
    
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved!</h4>
    <hr>
    <ul class="text-left">
      <% obj.errors.full_messages.each do |msg| %>
        <li ><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>

      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-white rounded", local: true) do | f | %>
      <div class= "form-group row mt-4">
        <%= f.label :username, class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter your username" %>
        </div>
      </div>
      <div class= "form-group row mt-4">
        <%= f.label :email, class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter your email" %>
        </div>
      </div>
      <div class= "form-group row mt-4">
        <%= f.label :password, class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter your password" %>
        </div>
      </div>



        <div class= "form-group row justify-content-md-center">
          <%= f.submit(@user.new_record? ? "Sign Up" :"Update", class: "col-2 btn btn-success") %>
        </div>
        <div class="card-footer text-muted">
          <a href=<%= users_path() %> class="btn btn-secondary"> Return</a>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="card-body">
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Username</th>
        <th scope="col">Articles</th>
        <th scope="col">Joined</th>
        <th scope="col">Updated</th>
        <th scope="col">Links</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.username, user, class: "text-secondary" %></td>
          <td><%= pluralize(user.articles.count, "article") %></td>
          <td><%= time_ago_in_words(user.created_at) %> ago</td>
          <td><%= time_ago_in_words(user.updated_at) %> ago</td>
          <td><%= link_to 'View Profile', user %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
<div class="card text-center mt-4">
  <div class="card-header">
    <h2>Update Profile</h2>
  </div>
  <%= render 'form' %>

</div>

app/views/users/index.html.erb
<div class="card text-center mt-4">
  <div class="card-header">
    <h2>Users</h2>
  </div>
  <div>
    <%= render 'user' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="card text-center mt-4">
  <div class="card-header">
    <h2>Signup</h2>
  </div>
  <%= render 'form' %>

</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="card text-center mt-4 mb-4">
    <div class="card-header">
      <h2><%= @user.username %>'s Profile</h2>
    </div>
    <div>
      <%= gravitar_for @user, size: 200 %>
      <%= link_to "edit your profile", edit_user_path(@user), class: "btn btn-outline-info mb-3" %>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="card text-center mt-4">
    <div class="card-header">
      <h2><%= @user.username %>'s Articles</h2>
    </div>
    <div>
      <%= render 'articles/article' %>
    </div>
  </div>
</div>